#!/usr/bin/env node
/**
 * One source of truth for what agents are told: the API's own TSDoc.
 *
 * Methods that back an MCP tool carry an `@agentTool <name>` block tag in
 * their docblock. This script runs TypeDoc over the public entry point and
 * emits `src/mcp/tool-docs.generated.ts` with two things:
 *
 *  - `TOOL_DOCS`: tool name → the tagged methods and their doc summaries,
 *    which the MCP server uses *as* its tool descriptions — so the text an
 *    agent reads is the text the API reference shows, and neither can
 *    drift from the other.
 *  - `AGENT_SURFACE`: a census of every public method on the document
 *    classes and the table model, each either tagged with its tool or
 *    `null`. The suite requires every `null` to be ledgered with a reason,
 *    so a new API method fails CI until someone decides — expose it or
 *    explain why not. Staleness is a build error, not a discovery.
 *
 * `--check` regenerates to memory and fails on drift, like proto:embed.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { Application, ReflectionKind } from "typedoc";
import type { DeclarationReflection, CommentDisplayPart } from "typedoc";

const OUT = new URL("../src/mcp/tool-docs.generated.ts", import.meta.url);
/** The classes whose public surface the census covers. */
const CENSUS_CLASSES = ["IWorkDocument", "PagesDocument", "NumbersDocument", "KeynoteDocument", "TableModel"];

function textOf(parts: readonly CommentDisplayPart[] | undefined): string {
  if (!parts) return "";
  return parts
    .map((p) => p.text)
    .join("")
    .replace(/\{@link\s+([^}|]+?)(?:\s*\|\s*([^}]+))?\}/g, (_, target: string, label?: string) =>
      (label ?? target).trim(),
    )
    .replace(/\s+/g, " ")
    .trim();
}

async function extract(): Promise<{
  tools: Map<string, { api: string; summary: string }[]>;
  census: { api: string; tool: string | null }[];
}> {
  const app = await Application.bootstrap(
    {
      entryPoints: ["src/index.ts"],
      excludeInternal: true,
      skipErrorChecking: true,
      readme: "none",
      logLevel: "Error",
      blockTags: [
        "@param", "@returns", "@remarks", "@example", "@deprecated",
        "@see", "@defaultValue", "@throws", "@agentTool",
      ],
    },
    [],
  );
  const project = await app.convert();
  if (!project) throw new Error("typedoc conversion failed");

  const tools = new Map<string, { api: string; summary: string }[]>();
  const census: { api: string; tool: string | null }[] = [];

  for (const className of CENSUS_CLASSES) {
    const cls = project.getChildByName(className) as DeclarationReflection | undefined;
    if (!cls) throw new Error(`census class ${className} not found among exports`);
    for (const child of cls.children ?? []) {
      if (child.kind !== ReflectionKind.Method) continue;
      if (child.flags.isPrivate || child.flags.isProtected) continue;
      if (child.inheritedFrom && className !== "IWorkDocument") continue; // count once, on the base
      const signature = child.signatures?.[0];
      const comment = signature?.comment ?? child.comment;
      const tag = comment?.blockTags.find((t) => t.tag === "@agentTool");
      const tool = tag ? textOf(tag.content) : null;
      const api = `${className}.${child.name}`;
      census.push({ api, tool });
      if (tool) {
        const summary = textOf(comment?.summary);
        if (!summary) throw new Error(`${api} is tagged @agentTool ${tool} but has no summary`);
        const entry = tools.get(tool) ?? [];
        entry.push({ api, summary });
        tools.set(tool, entry);
      }
    }
  }
  census.sort((a, b) => a.api.localeCompare(b.api));
  return { tools, census };
}

function render(data: Awaited<ReturnType<typeof extract>>): string {
  const lines: string[] = [
    "// Generated by scripts/generate-tool-docs.ts — do not edit.",
    "// The text here is extracted from the API's TSDoc; change the docblock",
    "// (and its @agentTool tag), then `npm run tooldocs`.",
    "",
    "/** Tool name → the tagged API methods and the doc summaries agents read. */",
    "export const TOOL_DOCS: ReadonlyMap<string, readonly { api: string; summary: string }[]> =",
    "  new Map([",
  ];
  for (const [tool, entries] of [...data.tools.entries()].sort()) {
    lines.push(`    [${JSON.stringify(tool)}, ${JSON.stringify(entries)}],`);
  }
  lines.push(
    "  ]);",
    "",
    "/** Every public method on the agent-facing classes, tool-tagged or not. */",
    "export const AGENT_SURFACE: readonly { api: string; tool: string | null }[] = [",
  );
  for (const { api, tool } of data.census) {
    lines.push(`  { api: ${JSON.stringify(api)}, tool: ${tool === null ? "null" : JSON.stringify(tool)} },`);
  }
  lines.push("];", "");
  return lines.join("\n");
}

const check = process.argv.includes("--check");
const data = await extract();
const generated = render(data);
if (check) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    // missing counts as stale
  }
  if (current !== generated) {
    console.error("src/mcp/tool-docs.generated.ts is stale; run `npm run tooldocs`");
    process.exit(1);
  }
  console.log("tool docs are current.");
} else {
  writeFileSync(OUT, generated);
  console.log(
    `wrote src/mcp/tool-docs.generated.ts (${data.tools.size} tools, ${data.census.length} methods)`,
  );
}
